<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime\TripUpdate\StopTimeUpdate;

/**
 * The relation between this StopTime and the static schedule.
 *
 * Protobuf type <code>Google.Transit.Realtime.TripUpdate.StopTimeUpdate.ScheduleRelationship</code>
 */
class ScheduleRelationship
{
    /**
     * The vehicle is proceeding in accordance with its static schedule of
     * stops, although not necessarily according to the times of the schedule.
     * At least one of arrival and departure must be provided. If the schedule
     * for this stop contains both arrival and departure times then so must
     * this update.
     *
     * Generated from protobuf enum <code>SCHEDULED = 0;</code>
     */
    const SCHEDULED = 0;
    /**
     * The stop is skipped, i.e., the vehicle will not stop at this stop.
     * Arrival and departure are // optional.
     *
     * Generated from protobuf enum <code>SKIPPED = 1;</code>
     */
    const SKIPPED = 1;
    /**
     * No data is given for this stop. The main intention for this value is to
     * give the predictions only for part of a trip, i.e., if the last update
     * for a trip has a NO_DATA specifier, then StopTimes for the rest of the
     * stops in the trip are considered to be unspecified as well.
     * Neither arrival nor departure should be supplied.
     *
     * Generated from protobuf enum <code>NO_DATA = 2;</code>
     */
    const NO_DATA = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ScheduleRelationship::class, \Google\Transit\Realtime\TripUpdate_StopTimeUpdate_ScheduleRelationship::class);

