<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\Alert\Cause instead.
     * @deprecated
     */
    class Alert_Cause {}
}
class_exists(Alert\Cause::class);
@trigger_error('Google\Transit\Realtime\Alert_Cause is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\Alert\Cause instead', E_USER_DEPRECATED);

