<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\Alert\Effect instead.
     * @deprecated
     */
    class Alert_Effect {}
}
class_exists(Alert\Effect::class);
@trigger_error('Google\Transit\Realtime\Alert_Effect is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\Alert\Effect instead', E_USER_DEPRECATED);

