<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\FeedHeader\Incrementality instead.
     * @deprecated
     */
    class FeedHeader_Incrementality {}
}
class_exists(FeedHeader\Incrementality::class);
@trigger_error('Google\Transit\Realtime\FeedHeader_Incrementality is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\FeedHeader\Incrementality instead', E_USER_DEPRECATED);

