<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\TranslatedString\Translation instead.
     * @deprecated
     */
    class TranslatedString_Translation {}
}
class_exists(TranslatedString\Translation::class);
@trigger_error('Google\Transit\Realtime\TranslatedString_Translation is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\TranslatedString\Translation instead', E_USER_DEPRECATED);

