<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\TripUpdate\StopTimeUpdate instead.
     * @deprecated
     */
    class TripUpdate_StopTimeUpdate {}
}
class_exists(TripUpdate\StopTimeUpdate::class);
@trigger_error('Google\Transit\Realtime\TripUpdate_StopTimeUpdate is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\TripUpdate\StopTimeUpdate instead', E_USER_DEPRECATED);

