<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\TripUpdate\StopTimeEvent instead.
     * @deprecated
     */
    class TripUpdate_StopTimeEvent {}
}
class_exists(TripUpdate\StopTimeEvent::class);
@trigger_error('Google\Transit\Realtime\TripUpdate_StopTimeEvent is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\TripUpdate\StopTimeEvent instead', E_USER_DEPRECATED);

