<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\TripDescriptor\ScheduleRelationship instead.
     * @deprecated
     */
    class TripDescriptor_ScheduleRelationship {}
}
class_exists(TripDescriptor\ScheduleRelationship::class);
@trigger_error('Google\Transit\Realtime\TripDescriptor_ScheduleRelationship is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\TripDescriptor\ScheduleRelationship instead', E_USER_DEPRECATED);

