<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\VehiclePosition\VehicleStopStatus instead.
     * @deprecated
     */
    class VehiclePosition_VehicleStopStatus {}
}
class_exists(VehiclePosition\VehicleStopStatus::class);
@trigger_error('Google\Transit\Realtime\VehiclePosition_VehicleStopStatus is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\VehiclePosition\VehicleStopStatus instead', E_USER_DEPRECATED);

