<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Realtime positioning information for a given vehicle.
 *
 * Generated from protobuf message <code>Google.Transit.Realtime.VehiclePosition</code>
 */
class VehiclePosition extends \Google\Protobuf\Internal\Message
{
    /**
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * optional TripDescriptor trip = 1;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.TripDescriptor trip = 1;</code>
     */
    private $trip = null;
    /**
     * Additional information on the vehicle that is serving this trip.
     * optional VehicleDescriptor vehicle = 8;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehicleDescriptor vehicle = 8;</code>
     */
    private $vehicle = null;
    /**
     * Current position of this vehicle.
     * optional Position position = 2;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.Position position = 2;</code>
     */
    private $position = null;
    /**
     * The stop sequence index of the current stop. The meaning of
     * current_stop_sequence (i.e., the stop that it refers to) is determined by
     * current_status.
     * If current_status is missing IN_TRANSIT_TO is assumed.
     * optional uint32 current_stop_sequence = 3;
     *
     * Generated from protobuf field <code>uint32 current_stop_sequence = 3;</code>
     */
    private $current_stop_sequence = 0;
    /**
     * Identifies the current stop. The value must be the same as in stops.txt in
     * the corresponding GTFS feed.
     * optional string stop_id = 7;
     *
     * Generated from protobuf field <code>string stop_id = 7;</code>
     */
    private $stop_id = '';
    /**
     * The exact status of the vehicle with respect to the current stop.
     * Ignored if current_stop_sequence is missing.
     * optional VehicleStopStatus current_status = 4 [default = IN_TRANSIT_TO];
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehiclePosition.VehicleStopStatus current_status = 4;</code>
     */
    private $current_status = 0;
    /**
     * Moment at which the vehicle's position was measured. In POSIX time
     * (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     * optional uint64 timestamp = 5;
     *
     * Generated from protobuf field <code>uint64 timestamp = 5;</code>
     */
    private $timestamp = 0;
    /**
     * optional CongestionLevel congestion_level = 6;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
     */
    private $congestion_level = 0;
    /**
     * optional OccupancyStatus occupancy_status = 9;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehiclePosition.OccupancyStatus occupancy_status = 9;</code>
     */
    private $occupancy_status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Transit\Realtime\TripDescriptor $trip
     *           The Trip that this vehicle is serving.
     *           Can be empty or partial if the vehicle can not be identified with a given
     *           trip instance.
     *           optional TripDescriptor trip = 1;
     *     @type \Google\Transit\Realtime\VehicleDescriptor $vehicle
     *           Additional information on the vehicle that is serving this trip.
     *           optional VehicleDescriptor vehicle = 8;
     *     @type \Google\Transit\Realtime\Position $position
     *           Current position of this vehicle.
     *           optional Position position = 2;
     *     @type int $current_stop_sequence
     *           The stop sequence index of the current stop. The meaning of
     *           current_stop_sequence (i.e., the stop that it refers to) is determined by
     *           current_status.
     *           If current_status is missing IN_TRANSIT_TO is assumed.
     *           optional uint32 current_stop_sequence = 3;
     *     @type string $stop_id
     *           Identifies the current stop. The value must be the same as in stops.txt in
     *           the corresponding GTFS feed.
     *           optional string stop_id = 7;
     *     @type int $current_status
     *           The exact status of the vehicle with respect to the current stop.
     *           Ignored if current_stop_sequence is missing.
     *           optional VehicleStopStatus current_status = 4 [default = IN_TRANSIT_TO];
     *     @type int|string $timestamp
     *           Moment at which the vehicle's position was measured. In POSIX time
     *           (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     *           optional uint64 timestamp = 5;
     *     @type int $congestion_level
     *           optional CongestionLevel congestion_level = 6;
     *     @type int $occupancy_status
     *           optional OccupancyStatus occupancy_status = 9;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * optional TripDescriptor trip = 1;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.TripDescriptor trip = 1;</code>
     * @return \Google\Transit\Realtime\TripDescriptor
     */
    public function getTrip()
    {
        return $this->trip;
    }

    /**
     * The Trip that this vehicle is serving.
     * Can be empty or partial if the vehicle can not be identified with a given
     * trip instance.
     * optional TripDescriptor trip = 1;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.TripDescriptor trip = 1;</code>
     * @param \Google\Transit\Realtime\TripDescriptor $var
     * @return $this
     */
    public function setTrip($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\TripDescriptor::class);
        $this->trip = $var;

        return $this;
    }

    /**
     * Additional information on the vehicle that is serving this trip.
     * optional VehicleDescriptor vehicle = 8;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehicleDescriptor vehicle = 8;</code>
     * @return \Google\Transit\Realtime\VehicleDescriptor
     */
    public function getVehicle()
    {
        return $this->vehicle;
    }

    /**
     * Additional information on the vehicle that is serving this trip.
     * optional VehicleDescriptor vehicle = 8;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehicleDescriptor vehicle = 8;</code>
     * @param \Google\Transit\Realtime\VehicleDescriptor $var
     * @return $this
     */
    public function setVehicle($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\VehicleDescriptor::class);
        $this->vehicle = $var;

        return $this;
    }

    /**
     * Current position of this vehicle.
     * optional Position position = 2;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.Position position = 2;</code>
     * @return \Google\Transit\Realtime\Position
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Current position of this vehicle.
     * optional Position position = 2;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.Position position = 2;</code>
     * @param \Google\Transit\Realtime\Position $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\Position::class);
        $this->position = $var;

        return $this;
    }

    /**
     * The stop sequence index of the current stop. The meaning of
     * current_stop_sequence (i.e., the stop that it refers to) is determined by
     * current_status.
     * If current_status is missing IN_TRANSIT_TO is assumed.
     * optional uint32 current_stop_sequence = 3;
     *
     * Generated from protobuf field <code>uint32 current_stop_sequence = 3;</code>
     * @return int
     */
    public function getCurrentStopSequence()
    {
        return $this->current_stop_sequence;
    }

    /**
     * The stop sequence index of the current stop. The meaning of
     * current_stop_sequence (i.e., the stop that it refers to) is determined by
     * current_status.
     * If current_status is missing IN_TRANSIT_TO is assumed.
     * optional uint32 current_stop_sequence = 3;
     *
     * Generated from protobuf field <code>uint32 current_stop_sequence = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentStopSequence($var)
    {
        GPBUtil::checkUint32($var);
        $this->current_stop_sequence = $var;

        return $this;
    }

    /**
     * Identifies the current stop. The value must be the same as in stops.txt in
     * the corresponding GTFS feed.
     * optional string stop_id = 7;
     *
     * Generated from protobuf field <code>string stop_id = 7;</code>
     * @return string
     */
    public function getStopId()
    {
        return $this->stop_id;
    }

    /**
     * Identifies the current stop. The value must be the same as in stops.txt in
     * the corresponding GTFS feed.
     * optional string stop_id = 7;
     *
     * Generated from protobuf field <code>string stop_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

    /**
     * The exact status of the vehicle with respect to the current stop.
     * Ignored if current_stop_sequence is missing.
     * optional VehicleStopStatus current_status = 4 [default = IN_TRANSIT_TO];
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehiclePosition.VehicleStopStatus current_status = 4;</code>
     * @return int
     */
    public function getCurrentStatus()
    {
        return $this->current_status;
    }

    /**
     * The exact status of the vehicle with respect to the current stop.
     * Ignored if current_stop_sequence is missing.
     * optional VehicleStopStatus current_status = 4 [default = IN_TRANSIT_TO];
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehiclePosition.VehicleStopStatus current_status = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentStatus($var)
    {
        GPBUtil::checkEnum($var, \Google\Transit\Realtime\VehiclePosition_VehicleStopStatus::class);
        $this->current_status = $var;

        return $this;
    }

    /**
     * Moment at which the vehicle's position was measured. In POSIX time
     * (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     * optional uint64 timestamp = 5;
     *
     * Generated from protobuf field <code>uint64 timestamp = 5;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Moment at which the vehicle's position was measured. In POSIX time
     * (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     * optional uint64 timestamp = 5;
     *
     * Generated from protobuf field <code>uint64 timestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * optional CongestionLevel congestion_level = 6;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
     * @return int
     */
    public function getCongestionLevel()
    {
        return $this->congestion_level;
    }

    /**
     * optional CongestionLevel congestion_level = 6;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehiclePosition.CongestionLevel congestion_level = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCongestionLevel($var)
    {
        GPBUtil::checkEnum($var, \Google\Transit\Realtime\VehiclePosition_CongestionLevel::class);
        $this->congestion_level = $var;

        return $this;
    }

    /**
     * optional OccupancyStatus occupancy_status = 9;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehiclePosition.OccupancyStatus occupancy_status = 9;</code>
     * @return int
     */
    public function getOccupancyStatus()
    {
        return $this->occupancy_status;
    }

    /**
     * optional OccupancyStatus occupancy_status = 9;
     *
     * Generated from protobuf field <code>.Google.Transit.Realtime.VehiclePosition.OccupancyStatus occupancy_status = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setOccupancyStatus($var)
    {
        GPBUtil::checkEnum($var, \Google\Transit\Realtime\VehiclePosition_OccupancyStatus::class);
        $this->occupancy_status = $var;

        return $this;
    }

}

