<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\VehiclePosition\CongestionLevel instead.
     * @deprecated
     */
    class VehiclePosition_CongestionLevel {}
}
class_exists(VehiclePosition\CongestionLevel::class);
@trigger_error('Google\Transit\Realtime\VehiclePosition_CongestionLevel is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\VehiclePosition\CongestionLevel instead', E_USER_DEPRECATED);

