<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/gtfs-realtime.proto3

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\VehiclePosition\OccupancyStatus instead.
     * @deprecated
     */
    class VehiclePosition_OccupancyStatus {}
}
class_exists(VehiclePosition\OccupancyStatus::class);
@trigger_error('Google\Transit\Realtime\VehiclePosition_OccupancyStatus is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\VehiclePosition\OccupancyStatus instead', E_USER_DEPRECATED);

